version: '3.8'
services:
  szi-ki-frontend:
    build:
      context: ./szi-ki-frontend
    ports:
      - "3105:80"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
  szi-ki-backend:
    build: 
      context: ./testapi
    depends_on:
      - mongodb
    ports:
      - "3104:3104"
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
