version: '3.8'
services:
  szi-ki-frontend:
    build:
      context: ./szi-ki-frontend
    ports:
      - "3105:80"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network
  create-mongo-db:
    build: 
      context: ./testapi
    depends_on:
      - mongodb
    command: bash -c "python create_collections.py"
  szi-ki-backend:
    build: 
      context: ./testapi
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
