# Dockerfile
FROM python:3.13.1
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["sh", "-c", "python create_collections.py && gunicorn --bind 0.0.0.0:3104 --workers 4 api:app"]
