# Basis-Image für Node.js
FROM node:22.14.0 AS build

# Arbeitsverzeichnis setzen
WORKDIR /app

# Abhängigkeiten kopieren und installieren
COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

# Quellcode kopieren
COPY . .

# React-App bauen
RUN npm run build

# Basis-Image für Apache
FROM debian:stable-slim AS runtime

RUN apt-get update && apt-get install -y apache2 apache2-utils

# Enable mod_rewrite module
RUN a2enmod rewrite

# Kopiere die gebaute React-App und die statischen Webserver-Dateien in das DocumentRoot von Apache
COPY --from=build /app/dist/ /var/www/html/
#COPY index.html /var/www/html/

# Exponiere Port 80
EXPOSE 3105

# Starte Apache im Vordergrund
CMD ["apache2ctl", "-D", "FOREGROUND"]
