# Basis-Image für Node.js
FROM node:22.14.0 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

COPY . .

RUN npm run build

# Basis-Image für Apache
FROM httpd:latest

# Erstelle Verzeichnisstruktur für Apache innerhalb von /apache2
RUN mkdir -p ./htdocs ./logs ./modules

# Kopiere die gebaute React-App in das neue Apache-Verzeichnis
COPY --from=build /app/dist/ ./htdocs/

# Starte Apache mit der angepassten Konfiguration
CMD ["/usr/local/apache2/bin/httpd", "-f", "./httpd.conf", "-D", "FOREGROUND"]

# Exponiere Port 3104
EXPOSE 3104
